### ISSUE TITLE
Kramdown does not seem to render math blocks

### ISSUE THREAD

**Issue by TMorville** [mmistakes/minimal-mistakes#735]
- [ ] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [x] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.1.1
- **`github-pages` or `jekyll` gem version:** github-pages 91 
- **Operating system:** OS x Sierra 10.12.2

---

## Expected behavior

Kramdown does not render math when using the `$$ \equation $$` syntax as prescribed on https://kramdown.gettalong.org/syntax.html#math-blocks. 

## Steps to reproduce the behavior

Here is a [link to my repo](https://github.com/TMorville/tmorville.github.io). As you can see under e.g. under [inverted pendulum.md](https://github.com/TMorville/tmorville.github.io/blob/master/_projects/inverted-pendulum.md) there should be two bits of math $$ x_t $$ and $$\theta_t$$ which should display as math. But when building (or serving), it [does not render](https://tmorville.github.io//projects/inverted-pendulum/).

I have forked Minimal Mistakes and implemented as shown. Everything else works fine. 

Here are my _congif.yml settings for markdown:

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

**Comment by mmistakes** [comment]
As per Krandown's docs you need to add the MathJax JavaScript library for it work. https://www.mathjax.org/

**Comment by justinrummel** [comment]
For scripts that I want to add on every page, I usually add them to the [_include/scripts.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/scripts.html) page.  I've also done some IF statements (which I'm sure are not the best way to do this) to see if I'm loading the main page or a "Search" page as seen on my repo: [scripts.html](https://github.com/justinrummel/jr.com-mm/blob/jr-branch/_includes/scripts.html)

**Comment by mmistakes** [comment]
You can add it to scripts.html or any of the two custom includes I've added to the theme for injecting scripts in the head or footer. 

/_includes/head/custom.html
/_includes/footer/custom.html

**Comment by mmistakes** [comment]
I'd add it using a conditional like @justinrummel suggested to avoid embedding the script on pages that don't need MathJax.

/_includes/scripts.html is probably the best place for it, but it can be added to one of the custom includes if you want to maintain to avoid messing with the main theme files.

Either way something like this:

```html
{% if page.mathjax %}
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
{% endif %}
```

And then in your post/page's YAML Front Matter you'd add `mathjax: true` if you wanted the script embedded.

**Comment by TMorville** [comment]
@mmistakes perfect. That solution works like a charm. Thanks.

**Comment by yuzhangbit** [comment]
I have a question related to this topic.  If I enable the mathjax like what @mmistakes  said,  the math equations can show up normally on the page of posts.  But the the author profile is gone in the post that is using the single layout.  As long as I remove the equation, the author profile will show up.  It seem the `$$` causes the problem.  Any solution to this problem?  Thank you ~

**Comment by mmistakes** [comment]
@yuzhangbit You have an example? My gut is telling me there's something with the MathJax script or possibly some sort of CSS interference. But without seeing the code it's hard to say.

**Comment by yuzhangbit** [comment]
@mmistakes  Thanks for your reply.  
[This](https://github.com/yuzhangbit/yuzhangbit.github.io) is my repo.
Here is the example [post](https://github.com/yuzhangbit/yuzhangbit.github.io/blob/master/_posts/2017-02-20-ompl-states-and-state-spaces.md). 
If you remove the latex math code 
```
$$SE2$$  
$$SE3$$
```  
the author profile will show up. 

I add the MathJax script 
```
{% if page.mathjax %}
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
{% endif %}
```  
to [this](https://github.com/yuzhangbit/yuzhangbit.github.io/blob/master/_includes/head/custom.html) file.

**Comment by mmistakes** [comment]
@yuzhangbit Does that post have the equation added? I'm not seeing any sort of layout issues and the author sidebar is present.

![img_6720](https://cloud.githubusercontent.com/assets/1376749/23144530/2fcd3890-f796-11e6-9e48-bbaf6bdc36f2.PNG)

**Comment by yuzhangbit** [comment]
Yes.  There are two latex math symbols(se2, se3).  The sidebar doesn't show up in the desktop browser.  I am using Chrome.   
![debug](https://cloud.githubusercontent.com/assets/6959109/23144799/25ebb4d0-f798-11e6-87c4-ab61b530662c.png)

**Comment by mmistakes** [comment]
I just tried it in Chrome on the desktop and the sidebar is there. 

![screen shot 2017-02-20 at 8 27 03 pm](https://cloud.githubusercontent.com/assets/1376749/23147187/f8792e8e-f7aa-11e6-9baf-f8632b45c1e4.png)

![screen shot 2017-02-20 at 8 24 48 pm](https://cloud.githubusercontent.com/assets/1376749/23147188/fadce71a-f7aa-11e6-981c-f47b00d988b7.png)

You sure you don't have any sort of adblocker extensions installed? They often kill social links and that would explain why the sidebar is gone. Other than that I really don't have any other suggestions as I can't seem to reproduce the issue.

**Comment by yuzhangbit** [comment]
@mmistakes   Thank you very much!   It seems it's the chrome extensions cause the problem.

**Comment by mmistakes** [comment]
So I rolled back to the non-beta version of Chrome and was able to reproduce it. The sidebar is there, but it disappears after the MathJax script loads and messes with the page's CSS.

It's doing a whole lot of stuff that hides the sidebar.

![screen shot 2017-02-20 at 8 45 27 pm](https://cloud.githubusercontent.com/assets/1376749/23147519/87a39d18-f7ad-11e6-86cd-c7b36446ada7.png)

You can edit the CSS for the `.sidebar` to fix it. Though this smells like a browser bug to me so it should be fixed when Chrome rolls out 57, as it works fine there and other browsers like Safari.

Removing the following from [`_sass/_sidebar.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_sidebar.scss#L10-L11) worked for me:

```css
-webkit-transform: translate3d(0, 0, 0);
transform: translate3d(0, 0, 0);
```

**Comment by yuzhangbit** [comment]
@mmistakes Ya, this works!  :+1:   The latest stable version of Opera browser is also able to reproduce this issue.

**Comment by benslack19** [comment]
Hi, I'm trying to render LaTex to one of my posts and I seem to be having trouble. Following mmistakes comment on Dec 28, 2016, I did the following:

To ```/_includes/scripts.html```, I added these few lines:
```
{% if page.mathjax %}
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
{% endif %}
```
Then to my post, I added ```mathjax: true``` in the front matter.

The github markdown file is [here](https://github.com/benslack19/benslack19.github.io/blob/master/_posts/2018-03-18-ML-logistic-regression-in-python-on-neuronal-classification/2018-03-18-ML-logistic-regression-in-python-on-neuronal-classification.md) and the corresponding website page is [here](https://benslack19.github.io/ML-logistic-regression-in-python-on-neuronal-classification/).

I'd sincerely appreciate any assistance.

**Comment by mmistakes** [comment]
@benslack19 Check your browser's console logs. I believe mathjax.org shut down their hosted copy of `MathJax.js`. You'll need to load the script from somewhere else.

![screen shot 2018-03-19 at 6 48 18 am](https://user-images.githubusercontent.com/1376749/37591402-d2e10a5e-2b41-11e8-92ec-217559bb1353.png)

Try this instead:

```html
{% if site.mathjax == true %}
<!-- MathJax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
{% endif %}
```

**Comment by benslack19** [comment]
OK thanks @mmistakes. I tried the snippet of code but still had some trouble. From looking at this [page](https://www.mathjax.org/cdn-shutting-down/), I tried changing the link in src to this

```https://rawgit.com/mhchem/MathJax-mhchem/master/mhchem.js```
or this
```https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0/mhchem.js```

and in both cases, I kept the suffix ```?config=TeX-AMS-MML_HTMLorMML``` but it's still not working for me. Any other suggestions? Sorry I'm mostly just doing trial and error to troubleshoot.

**Comment by mmistakes** [comment]
@benslack19 Other than the snippet I posted above that I have no other advice. I don't personally use LaTex so I'm not going to be much help.

As this isn't a theme issue I'd suggest asking for help on either the [Jekyll Talk forums](https://talk.jekyllrb.com/) or search through [Stackoverflow](https://stackoverflow.com/search?q=mathjax). This seems like a MathJax issue and you'll likely find help if you widen your search some.

**Comment by benslack19** [comment]
This makes sense, thanks.

**Comment by benslack19** [comment]
Hi @mmistakes just wanted to let you know that I got this working. I followed this and the solution from @yuzhangbit. 

*You can add it to scripts.html or any of the two custom includes I've added to the theme for injecting scripts in the head or footer.
/_includes/head/custom.html*

The solution you posted above (dnjs.cloudflare.com hosting) worked when I put it  in the /_includes/head/custom.html.

Thank you!

**Comment by benslack19** [comment]
Hi @asarkar ,

I hadn't updated my blog in a while but my last post had some rendering of Latex code.

You can see the actual webpage [here](https://benslack19.github.io/ML-logistic-regression-in-python-on-neuronal-classification/) and how I wrote it in my markdown [here](https://github.com/benslack19/benslack19.github.io/blob/master/_posts/2018-03-24-ML-logistic-regression-in-python-on-neuronal-classification/2018-03-24-ML-logistic-regression-in-python-on-neuronal-classification.md).

You can see from the above conversation where I faced some sticking points. Hope this is useful and good luck.

Cheers,
Ben

**Comment by sudhirln92** [comment]
I tried above a few codes, but could not able to solve for mine. Later use below code, which solved the mathjax problem.

`
{% if page.mathjax %}
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
{% endif %}

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
    "HTML-CSS": { availableFonts: ["TeX"] }
  });
</script>`

**Comment by benslack19** [comment]
Thank you @sudhirln92. I was updating something else and that snippet helped.

**Comment by asarkar** [comment]
Note that MathJax 3 is a complete rewrite of MathJax 2, and there are many breaking changes. They provide a website for converting your v2 config to v3.
https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html
