### ISSUE TITLE
Javascript Changes Not being applied

### ISSUE THREAD

**Issue by DaveBben** [mmistakes/minimal-mistakes#874]
- [ ] This is a question about using the theme.
- [x ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ x] I have updated all gems with `bundle update`.
- [x ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

**Minimal Mistakes version:4.2.2
**github-pages or jekyll gem version:3.4.0
**Operating system: Ubuntu 16.04

---

## Expected behavior

When I make a changes to _main.js, then rebuid using npm, the changes are applied and in the _main.min.js file. However, when I build the site, the _main.min.js file remains unaltered.

### First
I delete the following from main.js
`  // Follow menu drop down
  $(".author__urls-wrapper button").on("click", function() {
    $(".author__urls").fadeToggle("fast", function() {});
    $(".author__urls-wrapper button").toggleClass("open");
  });`

The I run _npm run build:js_

The main.min.js file is produced and does not contain the deleted code. 
FInally I run: 

#### _bundle exec jekyll _build__

In the Site folder, the main.min.js file still contains the deleted code as well as main.js file.
I've also tried with 

####  _bundle exec jekyll _build --incremental__ 

and the same output occures.

**Comment by mmistakes** [comment]
Smells like a Jekyll issue and not the theme. If the script is updated  after you run `build:js` then perhaps it's a caching issue. Have you tried running `jekyll clean` to wipe all your caches and the `_site` folder?

Other than that I'm out of ideas. Theme files all sounds right, something is going on with Jekyll during the build. Could be some sort of bug you're encountering. Gem theme or is it a fork of the repo?

**Comment by DaveBben** [comment]
I'm using the Gem theme. Yeah, it might be a Jekyll issue then I have no idea. So far, I've tried the following:

1. Uninstalling and reinstalling Jekyll and all the dependencies
2 . Clearing the cache for node js
3. Using the comman npm run watch:js and npm run build:js
4. Using bundle exec jekyll buid --watch

The thing is, I see the change is happening within the development folders. Both the main.js and main.min.js have been changed. But for some reason, the files in the site folder all contain the old unmodified code.

Just to make sure I'm not missing something, here is my gemfile and includes and excludes
source "https://rubygems.org"

gem "jekyll", "~> 3.4.0"
gem "minimal-mistakes-jekyll"
gem 'jekyll-admin', group: :jekyll_plugins

Includes and excludes in _config.yml


# Reading Files
include:
  - .htaccess
  - _pages

# exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn

**Comment by mmistakes** [comment]
It is indeed a Jekylk issue. This same exact problem came up before and filed a ticket, forgot all about that.

https://github.com/jekyll/jekyll/issues/5676

Not sure if it when there will be a fix. The problem is Jekyll will only override theme gem assets that have YAML Front Matter, like /assets/css/main.scss. That's why it's ignoring your modified JS files on build.

**Comment by mmistakes** [comment]
Closing as this an upstream issue with Jekyll.
Related #722

**Comment by mmistakes** [comment]
@DaveBben I found a workaround until this is fixed upstream. If I add YAML Front Matter to `main.min.js` it can be overridden. In the next release of MM I'll push it out. All you'll have to do is add:

```
---
---
```

to the top of your modified `/assets/js/main.min.js` file and it should override the theme gem's version.

**Comment by DaveBben** [comment]
Oh wow you're awesome! Thanks, that would be so helpful.  Hoepfully they'll get the Jekyll issued fixed at some point.

**Comment by mmistakes** [comment]
Hopefully that's soon, think I saw it was slated for Jekyll `3.5`.

Just [pushed an update](https://github.com/mmistakes/minimal-mistakes/releases/tag/4.3.0) to MM. Run `bundle update` and you should get version `4.3.0`. Let me know how it works out.

**Comment by DaveBben** [comment]
Yess! It works perfectly! The javascript file now reflects the changes. Thanks for all of your help.

**Comment by mmistakes** [comment]
Fantastic! Thanks for checking.

**Comment by Harrypotterrrr** [comment]
@mmistakes  Sorry for my simple question.. 
I met the same problem and append YAML Front Matter to `/asset/main.min.js` but it still doesn't change after run 'bundle exec jekyll serve`  
Could you tell me what the difference is between `/asset/_main.js` and `/asset/main.min.js` ?  
I want to only write code in `_main.js`, so I wonder if `/asset/main.min.js` is updated automatically.

**Comment by mmistakes** [comment]
@Harrypotterrrr `/assets/js/_main.js` is the source JavaScript that is combined with some other scripts like jQuery and plugins, then minified into `main.min.js`. This is the file the theme uses.

So if you make changes to `_main.js` you will need to run the build script as described in the [theme's documentation](https://mmistakes.github.io/minimal-mistakes/docs/javascript/). This will create the `main.min.js` file with any changes you've made.

**Comment by Harrypotterrrr** [comment]
wow, Appreciate your help!
